GameStore/WebUI/Models/GamesListViewModel.cs
using System.Collections.Generic;
using Domain.Entities;

namespace WebUI.Models
{
    public class GamesListViewModel
    {


        public IEnumerable<Game> Games { get; set; }
        public PagingInfo PagingInfo { get; set; }
        public string CurrentCategory { get; set; }
    }
}

GameStore/WebUI/Models/PagingInfo.cs
using System;

namespace WebUI.Models
{
    public class PagingInfo
    {

        /// <summary>
        /// Кол-во товаров
        /// </summary>
        public int TotalItems { get; set; }

        /// Кол-во товаров на одной странице
        public int ItemsPerPage { get; set; }

        /// Номер текущей страницы
        public int CurrentPage { get; set; }

        /// Общее кол-во страниц
        public int TotalPages
        {
            get { return (int)Math.Ceiling((decimal)TotalItems / ItemsPerPage); }
        }


    }
}

GameStore/WebUI/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.Abstract;
using WebUI.Models;



namespace WebUI.Controllers
{
    public class GameController : Controller
    {

        private IGameRepository repository;
        public int pageSize = 4;


        public GameController(IGameRepository repo)
        {
            repository = repo;
        }


        public ViewResult List(string category, int page = 1)
        {
            //return View(repository.Games);

            /*
            var result = repository.Games
                .OrderBy(game => game.GameId)
                .Skip((page - 1)*pageSize)
                .Take(pageSize);
            return View(result);
            */
            GamesListViewModel model = new GamesListViewModel()
            {
                Games = repository.Games
                    .Where(p => category == null || p.Category == category)
                    .OrderBy(game => game.GameId)
                    .Skip((page - 1)*pageSize)
                    .Take(pageSize),
                PagingInfo = new PagingInfo()
                {
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    TotalItems = repository.Games
                    .Count(p => category == null || p.Category == category)
                },
                CurrentCategory = category
                
            };
            if (model.Games.Count() == 0)
            {
                ViewBag.ErrorMessage = "model.Games == null";
                return View("Error");
            }

            return View(model);

        }

    }




   
}

GameStore/WebUI/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.Abstract;
using Domain.Entities;

namespace WebUI.Controllers
{
    public class NavController : Controller
    {
        private IGameRepository repository;

        public NavController(IGameRepository repo)
        {
            this.repository = repo;
        }

        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;

            /*
            IEnumerable<string> categories = repository.Games
                .Select(game => game.Category)
                .Distinct()
                .OrderBy(x => x);
            */

            ViewBag.CountGames = repository.Games.Count();

            IEnumerable<IGrouping<string, Game>> categoriesGroup = repository.Games
                .GroupBy(game => game.Category)
                .OrderBy(x => x.Key);
           
            return PartialView(categoriesGroup);

        }
    }
}

GameStore/WebUI/Views/Game/List.cshtml
@using WebUI.Models
@using WebUI.HtmlHelpers
@model GamesListViewModel

@{
    ViewBag.Title = "Товары";
}
<div class="row">
    <div class="pull-right">
        @Html.PageLinks(Model.PagingInfo,
        x => Url.Action("List", new { page = x, category = Model.CurrentCategory }))
    </div>
</div>
@foreach (var p in @Model.Games)
{
    @Html.Partial("_GameSummary", p)
}




 

GameStore/WebUI/Views/Game/_GameSummary.cshtml
@model Domain.Entities.Game


<div class="well">
    <h3>
        <strong>@Model.Name</strong>
        <span class="pull-right label label-primary">@Model.Price.ToString("# руб")</span>
    </h3>
    <span class="lead">@Model.Description</span>
    <div class="container">
        <div class="row">
            @Html.RouteLink(Model.Category,
               new { controller = "Game", action = "List", category = Model.Category, page = 1 },
               new { @class = "btn btn-default btn-sm " })
        </div>
    </div>
</div>

GameStore/WebUI/Views/Nav/Menu.cshtml
@model IEnumerable<IGrouping<string, Domain.Entities.Game>>

<ul class="nav">
    <li>
        @*@Html.ActionLink("Все товары", "List", "Game", null,
        new { @class = "btn btn-block btn-default btn-lg" })*@


        <a href="@(Url.RouteUrl(new {controller = "Game", action = "List", page = 1}))"
           class="@("btn btn-block btn-default btn-lg" + (null == ViewBag.SelectedCategory ? " btn-primary" : ""))">
            Все товары <span class="badge">@ViewBag.CountGames</span>
        </a>
    </li>

    @foreach (var link in Model)
    {
        <li>
            <a href="@(Url.RouteUrl(new {controller = "Game", action = "List", category = link.Key, page = 1}))"
               class="@("btn btn-block btn-default btn-lg" + (link.Key == ViewBag.SelectedCategory ? " btn-primary" : ""))">
                @link.Key <span class="badge">@link.Count()</span>
            </a>
        </li>
        }
    </ul>

GameStore/WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css"/>
    <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("GameStore - магазин компьютерных игр", null, null, new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    
                </ul>
            </div>
        </div>
    </div>
<div class="container">
    <div class="row panel">

        <div id="categories" class="col-xs-3">
           
                <div class="control-label">
                    @Html.Action("Menu", "Nav")
                </div>
           
        </div>

        <div class="col-xs-9">
            @RenderBody()
        </div>

    </div>
</div>

<hr/>

<footer>
    <p class="text-center">&copy; @DateTime.Now.Year - GameStore</p>
</footer>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>